### ISSUE TITLE
Error upon logging in/reload screen

### ISSUE THREAD

**Issue by TiaMarieG** [voidzone/PersonalLootHelper#5]
Hello! So glad that PLH is back!

Upon logging in/reloading my screen I get this error message every time:

11x ...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:1646: attempt to compare nil with number
[string "@PersonalLootHelper/PersonalLootHelper-Core.lua"]:1646: in function <...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:1537>
[string "@PersonalLootHelper/PersonalLootHelper-Core.lua"]:2545: in function <...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:2502>
[string "@PersonalLootHelper/PersonalLootHelper-Core.lua"]:2552: in function <...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:2550>

Locals:
closeButton = Button {
 0 = <userdata>
}
resizeButton = Button {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "v2.30"
(*temporary) = nil
(*temporary) = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1634
(*temporary) = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1634
(*temporary) = nil
(*temporary) = PLH_LootedItemsFrame {
 0 = <userdata>
 BorderLeftMiddle = Texture {
 }
 BorderBottomLeft = Texture {
 }
 BorderTopRight = Texture {
 }
 BorderBottomMiddle = Texture {
 }
 scrollbar = Slider {
 }
 closeButton = Button {
 }
 scrollframe = ScrollFrame {
 }
 Bg = Texture {
 }
 BorderTopMiddle = Texture {
 }
 BorderTopLeft = Texture {
 }
 BorderRightMiddle = Texture {
 }
 BorderBottomRight = Texture {
 }
}
(*temporary) = 399.999847
(*temporary) = 140.000015
(*temporary) = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1043
(*temporary) = "attempt to compare nil with number"
lootedItemsFrame = PLH_LootedItemsFrame {
 0 = <userdata>
 BorderLeftMiddle = Texture {
 }
 BorderBottomLeft = Texture {
 }
 BorderTopRight = Texture {
 }
 BorderBottomMiddle = Texture {
 }
 scrollbar = Slider {
 }
 closeButton = Button {
 }
 scrollframe = ScrollFrame {
 }
 Bg = Texture {
 }
 BorderTopMiddle = Texture {
 }
 BorderTopLeft = Texture {
 }
 BorderRightMiddle = Texture {
 }
 BorderBottomRight = Texture {
 }
}
SaveMainWindowPosition = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1510
RestoreMainWindowPosition = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1524
scrollbar = Slider {
 ScrollDownButton = PLH_LootedItemsFrameScrollDownButton {
 }
 scrollStep = 10
 ThumbTexture = PLH_LootedItemsFrameThumbTexture {
 }
 ScrollUpButton = PLH_LootedItemsFrameScrollUpButton {
 }
 0 = <userdata>
}
HideOffScreenWidgets = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1043
scrollFrame = ScrollFrame {
 0 = <userdata>
 content = Frame {
 }
}
contentFrame = Frame {
 0 = <userdata>
}
welcomeLabel = nil
UpdateLootedItemsDisplay = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1268

**Comment by voidzone** [comment]
Should be resolved in 2.31

**Comment by Revnae** [comment]
still getting error 




1x ...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:1646: attempt to compare nil with number
[string "@PersonalLootHelper/PersonalLootHelper-Core.lua"]:1646: in function <...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:1537>
[string "@PersonalLootHelper/PersonalLootHelper-Core.lua"]:2545: in function <...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:2502>
[string "@PersonalLootHelper/PersonalLootHelper-Core.lua"]:2552: in function <...ddOns/PersonalLootHelper/PersonalLootHelper-Core.lua:2550>

Locals:
closeButton = Button {
 0 = <userdata>
}
resizeButton = Button {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "v2.30"
(*temporary) = nil
(*temporary) = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1634
(*temporary) = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1634
(*temporary) = nil
(*temporary) = "Button"
(*temporary) = nil
(*temporary) = PLH_LootedItemsFrame {
 0 = <userdata>
 BorderLeftMiddle = Texture {
 }
 BorderBottomLeft = Texture {
 }
 BorderTopRight = Texture {
 }
 BorderBottomMiddle = Texture {
 }
 scrollbar = Slider {
 }
 closeButton = Button {
 }
 scrollframe = ScrollFrame {
 }
 Bg = Texture {
 }
 BorderTopMiddle = Texture {
 }
 BorderTopLeft = Texture {
 }
 BorderRightMiddle = Texture {
 }
 BorderBottomRight = Texture {
 }
}
(*temporary) = nil
(*temporary) = "attempt to compare nil with number"
lootedItemsFrame = PLH_LootedItemsFrame {
 0 = <userdata>
 BorderLeftMiddle = Texture {
 }
 BorderBottomLeft = Texture {
 }
 BorderTopRight = Texture {
 }
 BorderBottomMiddle = Texture {
 }
 scrollbar = Slider {
 }
 closeButton = Button {
 }
 scrollframe = ScrollFrame {
 }
 Bg = Texture {
 }
 BorderTopMiddle = Texture {
 }
 BorderTopLeft = Texture {
 }
 BorderRightMiddle = Texture {
 }
 BorderBottomRight = Texture {
 }
}
SaveMainWindowPosition = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1510
RestoreMainWindowPosition = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1524
scrollbar = Slider {
 ScrollDownButton = PLH_LootedItemsFrameScrollDownButton {
 }
 scrollStep = 10
 ThumbTexture = PLH_LootedItemsFrameThumbTexture {
 }
 ScrollUpButton = PLH_LootedItemsFrameScrollUpButton {
 }
 0 = <userdata>
}
HideOffScreenWidgets = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1043
scrollFrame = ScrollFrame {
 0 = <userdata>
 content = Frame {
 }
}
contentFrame = Frame {
 0 = <userdata>
}
welcomeLabel = nil
UpdateLootedItemsDisplay = <function> defined @PersonalLootHelper/PersonalLootHelper-Core.lua:1268

**Comment by voidzone** [comment]
You were still running 2.30 not 2.31

**Comment by TiaMarieG** [comment]
I just re-installed this from curseforge as I'm still experiencing the error as well and even with a fresh install it still is being listed as 2.3 in the error message.

**Comment by voidzone** [comment]
Alright, I can't reproduce it in-game with a fresh install.

With the game not running, I'd recommend editing your account-level `\World of Warcraft\_retail_\WTF\Account\NAME\SavedVariables\PersonalLootHelper.lua` and deleting the line with `["PLH_LAST_SEEN_MESSAGE_VERSION"]` then save and see if it's gone on next launch.

**Comment by voidzone** [comment]
Nevermind, found the problem. Had to reload after a fresh install.
